### ISSUE TITLE
Multiple sessions

### ISSUE THREAD

**Issue by nielsdB97** [pjchender/react-use-opentok#19]
Hi! First of all I would like to thank you for building a hooks variant of the OpenTok library. I think it feels way nicer and less bloated than the official one based on components.

For the application that I'm building I need to connect to multiple OpenTok sessions at the same time. Would that be possible with this library?
Thank you in advance!

**Comment by pjchender** [comment]
Hi! @nielsdB97 Thanks for your appreciation. I want to make sure that whether you need to initialize many different sessions? Or you need to create multiple connections to one session?

**Comment by nielsdB97** [comment]
Thanks for getting back to me @pjchender  :slightly_smiling_face:
I have multiple 'clients' that I fetch from a custom API, every one of which has a session. This amount of 'clients'/sessions is variable. This is why I have to loop over the API response, to then initialize an OpenTok session for every 'client'.

I don't know if this is possible using this library, but I hope it is! If so, would you be able to give me some example code of how I could create multiple OpenTok sessions using this library? If it's not possible that's too bad, maybe we could figure out a way but otherwise I'll unfortunately have to resort to using the official OpenTok library.

**Comment by pjchender** [comment]
@nielsdB97 Sorry, the current library did not support creating multiple sessions yet.
