### ISSUE TITLE
Creating a publisher without publishing to the session

### ISSUE THREAD

**Issue by KeysonG** [pjchender/react-use-opentok#23]
Thank you for the great library, really like the hooks implementation. 

OT provides an api to initialise a publisher without actually publishing to the session. Would it be possible to split the functionality between creating a publisher and actually publishing to the session?

**Comment by andyyou** [comment]
It could be, but this library is made for reducing configuration, operation, and simplify the common scenario. Could you explain why you need that?

**Comment by KeysonG** [comment]
a camera preview Component for instance so I’ll only want to create a
publisher without actually publishing to the session,

Op vr 2 okt. 2020 om 10:26 schreef andyyou <notifications@github.com>

**Comment by pjchender** [comment]
@KeysonG. Thanks for your suggestion.

If you only want to create a publisher without publishing to the session. Please use the original `OT` object provided by `@opentok/client`. Cause you do not need to keep these data in the state, it's more simple to use
`OT.initPublisher` directly, such as:

```js
OT.initPublisher('publisher', {
  publishAudio: false,
  height: '100%',
  width: '100%',
});
```

In our App using OpenTok, we also face the situation of creating a publisher without publishing, and we do it like above. Any further opinions are welcome.

**Comment by andyyou** [comment]
@pjchender @KeysonG I am considering if there is a `preview` method, and how to handle re-use the same publisher again.

**Comment by andyyou** [comment]
@pjchender After considered for a while. To avoid break current design I would like to provide additional methods that

* `initPublisher` - initialize publisher without publish
* `removePublisher` - it can only remove publisher without publish
* `publishPublisher` - publish the publisher means if use `initPublisher` + `publishPublisher` = `publish` then you should use `unpublish` 

How you guys think about this. This solution is focus on compatible.

**Comment by KeysonG** [comment]
I like this design a lot, would definitely clean up some code but I also get @pjchender's solution.

**Comment by pjchender** [comment]
@KeysonG Please check the newest release #25
