### ISSUE TITLE
How to check if a signal has failed becouse of an error

### ISSUE THREAD

**Issue by nicoladj77** [pjchender/react-use-opentok#24]
Looking at your source code, it's not clear what I should do to understand if sending a signal resulted in an error. From what I see all you do is log. Is this intentional?

```
  const sendSignal = useCallback(
    ({ type, data, to, completionHandler }) => {
      if (!isSessionConnected) {
        throw new Error('[ReactUseOpenTok] sendSignal: Session is not connected');
      }

      let signal = {
        data,
        ...type && { type },
        ...to && { to },
      }

      session.signal(signal, error => {
        if (error) {
          console.warn('[ReactUseOpenTok] sendSignal error: ' + error.message);
        } else if (typeof completionHandler === 'function') {
          completionHandler();
        }
      });
    },
    [isSessionConnected, session]
  );
```

**Comment by andyyou** [comment]
@pjchender Is that forgot throw the error?

**Comment by pjchender** [comment]
@nicoladj77 Please check the newest release #25

**Comment by nicoladj77** [comment]
@pjchender @andyyou I don't see anything in that release regarding signals. Am I missing something?

**Comment by andyyou** [comment]
@nicoladj77  Its actually nothing change for your problem. I think @pjchender misunderstand with a different issue XDDD
Sorry for that I sent a PR #26 you can check out is that you need. Or you want to put error into `completionHandler`
