### ISSUE TITLE
hasAudio and hasVideo not updating in stream

### ISSUE THREAD

**Issue by danielgent** [pjchender/react-use-opentok#28]
Hello :wave: 

First of all, I'm loving your library!  I've been using it to code stuff that wouldn't be possible with the official libraries.  Much :heart: 

Did you know that `hasAudio` and `hasVideo` are not being updated in `streams`?

I'm currently doing a workaround like this:

```
	const handleStreamPropertyChanged = useCallback(
		(e) => {
			const { newValue, changedProperty, stream } = e;
			const { id } = stream;
			setStreamProperties({
				...streamProperties,
				[id]: {
					...streamProperties[id],
					[changedProperty]: newValue,
				},
			});
		},
		[streamProperties, setStreamProperties],
	);

	useEffect(() => {
		if (!isSessionConnected) {
			return () => {};
		}

		session.on('streamPropertyChanged', handleStreamPropertyChanged);
		return () => {
			session.off('streamPropertyChanged', handleStreamPropertyChanged);
		};
	}, [handleStreamPropertyChanged, isSessionConnected, session]);
```
  _(based on your Register session events example!)_

  But I think it would be possible to fix this functionality in your library!  Is there any reason it's not working?

  I think it could be fixed like this.  In index.js
  
```
useSessionEventHandler('streamPropertyChanged', handleStreamPropertyChanged, session);
```

And then you would just need a new action e.g. `STREAM_PROPERTY_CHANGED`, which the reducer would then 
    

```
    case STREAM_PROPERTY_CHANGED: {
      return {
        ...state,
        subscribers: [
          ...state.streams...

          // and some code here like my example above

        ],
      };
```

It doesn't look like it's too much work (but there might be something I'm missing), and you have really nice tests

I'd be happy to try if you think this would be worth it

OR IF NOT I'll keep using my workaround

Thanks,
Dan

**Comment by pjchender** [comment]
Hi Dan,

Thanks for your opinion. I think it really makes sense. Is it possible to send a PR and I will check it. If there is any problem while running the test or starting the development, I am willing to help.
