### ISSUE TITLE
Not compatible with React 17

### ISSUE THREAD

**Issue by mmmaxi** [pjchender/react-use-opentok#30]
Are there any plans of upgradeing to React 17? I get the following error:

`
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.0" from react-use-opentok@2.3.1
npm ERR! node_modules/react-use-opentok
npm ERR!   react-use-opentok@"^2.3.1" from the root project
`

**Comment by pjchender** [comment]
Sure. It will compatible to React v17, or make a PR is appreciated.

**Comment by jwglimois** [comment]
We've created a PR: https://github.com/pjchender/react-use-opentok/pull/31
